services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      DB_USER: root
      DB_PASSWORD: 12345      # local default
      DB_NAME: fastapi_db     # local default
      DB_HOST: db
      DB_PORT: 3306
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests   # mount tests folder
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: fastapi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345   # local default
      MYSQL_DATABASE: fastapi_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
