name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Start Docker Compose Services
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if docker exec fastapi_db mysqladmin ping -h "localhost" --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Ensure DB tables created
        run: |
          # ensure Python can import
          docker exec -e PYTHONPATH=/app -w /app fastapi_app \
            python -c "from app.database import Base, engine; import app.models; Base.metadata.create_all(bind=engine); print('tables ensured')"

      - name: Run flake8
        run: docker exec fastapi_app flake8 app

      - name: Run tests inside container
        run: |
          # make sure tests run from /app and Python can import package
          docker exec -e PYTHONPATH=/app -w /app fastapi_app pytest -q --disable-warnings tests/


      - name: Build Docker image
        run: docker build -t noorfatima21/fastapi-app .

      - name: Push Docker image
        run: docker push noorfatima21/fastapi-app
